# Protocoale de comunicatii:
# Laborator 10: Mail
# Makefile

CFLAGS = -Wall

# Portul pe care asculta serverul (de completat)
PORT = 4242

# Adresa IP a serverului (de completat)
IP_SERVER = 127.0.0.1

default: send_mail

# Compileaza send_mail.c
send_mail: send_mail.c

clean:
	rm -f send_mail
